- src/main/java/iampotato/iampotato/domain/discount/application/DiscountService.java
- src/main/java/iampotato/iampotato/domain/discount/dao/DiscountRepository.java
- src/main/java/iampotato/iampotato/domain/discount/domain/Discount.java
- src/main/java/iampotato/iampotato/domain/discount/domain/DiscountDay.java
- src/main/java/iampotato/iampotato/domain/store/api/StoreApi.java
- src/main/java/iampotato/iampotato/domain/store/application/StoreService.java
- src/main/java/iampotato/iampotato/domain/store/dao/StoreRepository.java
- src/main/java/iampotato/iampotato/domain/store/domain/Address.java
- src/main/java/iampotato/iampotato/domain/store/domain/Store.java
- src/main/java/iampotato/iampotato/domain/store/dto/StoreTodayDiscountRequest.java
- src/main/java/iampotato/iampotato/domain/store/dto/StoreTodayDiscountResponse.java
- src/test/java/iampotato/iampotato/domain/store/application/StoreServiceTest.java
- #38 
<br/>
- 오늘의할인 페이지 개발
오늘의 할인 페이지를 위한 api, repository, service, dto, test 가 추가되었습니다.
그리고 추가로 수정한 부분입니다.
Store 엔티티를 builder 패턴으로 변경했습니다. 엔티티의 경우 builder 패턴이 가독성이 더 좋다고 생각했습니다.
Store 의 내장타입 Address 의 zipNum, roadNum 을 int -> String 으로 변경했습니다. int 로 연산을 할 필요가 없다고 판단해 String 으로 변경했습니다.
Discount 를 저장하기위한 repository, service 가 추가되었습니다
Discount 에서 요일 저장을 String 이 아닌 Enum 타입으로 변경했습니다. 요일을 명확히 명시하기 위해서 입니다.
<br/>
- Store
- Address
- StoreRepository
- StoreService
- StoreApi
- StoreServiceTest
- StoreTodayDiscountRequest
- StoreTodayDiscountResponse
- Discount
- DiscountDay
- DiscountRepository
- DiscountService
<br/>
- x
<br/>
- x
> Feature/develop today discounting(#38)

- src/main/java/iampotato/iampotato/domain/store/api/StoreApi.java
- #54 
<br/>
- swagger 에서 store api 를 이해하기 쉽게 설명을 추가합니다.
<br/>
- StoreApi
<br/>
- 어노테이션을 활용했습니다.
<br/>
- x
> feat : add description (#52)

- src/main/java/iampotato/iampotato/InitDb.java
- #56 
<br/>
- 실제 서버에서 테스트 할 수 있게 테스트 데이터 넣는 클래스 개발
<br/>
-
<br/>
-
<br/>
-
> feat : add InitDb (#56)

- src/main/java/iampotato/iampotato/global/config/SecurityConfig.java
- https://github.com/sayingpotato/Backend/issues/51
<br/>
- CORS 이슈를 해결하기 위해 cors()관련 메서드를 spring security filter에 추가했었는데 에러가 발생
<br/>
- SecurityConfig
<br/>
- cors 메서드 사용이 잘못되어 cors 설정 관련 bean을 추가
- https://toycoms.tistory.com/37
<br/>
- 없습니다.
> fix : fix some errors about cors (#51)

- src/main/java/iampotato/iampotato/global/config/SecurityConfig.java
- #60 
<br/>
- spring filter 단에서 cors 처리를 하여 spring mvc 에서 설정한 cors 가 안먹는 문제 해결
<br/>
- SecurityConfig
<br/>
- fiter 단의 cors 를 따로 설정안해두어 자동으로 spring mvc cors 를 따라가도록 설정
<br/>
- x
> feat : modify cors (#60)

- .gitignore
- build.gradle
- src/main/java/iampotato/iampotato/domain/store/api/StoreApi.java
- src/main/java/iampotato/iampotato/domain/store/application/StoreService.java
- src/main/java/iampotato/iampotato/domain/store/dao/StoreRepository.java
- src/main/java/iampotato/iampotato/domain/store/dto/search/StoreSearchRequest.java
- src/main/java/iampotato/iampotato/domain/store/dto/search/StoreSearchResponse.java
- src/main/java/iampotato/iampotato/global/config/QuerydslConfig.java
- src/main/java/iampotato/iampotato/global/config/SwaggerConfig.java
- src/test/java/iampotato/iampotato/domain/store/application/StoreServiceTest.java
- #66 
<br/>
- 검색 기능 개발
- 토큰발급 기능에 의해 Swagger 에서 테스트할수 없었던 점을 해결(스웨거 설정파일추가)
- Querydsl 라이브러리를 추가하여 쿼리작성 편의성 증가
<br/>
- ,gitignore
- build.gradle
- QuerydslConfig
- SwaggerConfig
- StoreSearchRequest
- StoreSearchResponse
- StoreService
- StoreRepository
- StoreApi
- StoreServiceTest
<br/>
- x
<br/>
- x
> Feat/develop search(#66)

- src/main/java/iampotato/iampotato/InitDb.java
- src/main/java/iampotato/iampotato/domain/item/domain/Item.java
- src/main/java/iampotato/iampotato/domain/itemoption/domain/ItemOption.java
- src/main/java/iampotato/iampotato/domain/order/api/OrderApi.java
- src/main/java/iampotato/iampotato/domain/order/application/OrderService.java
- src/main/java/iampotato/iampotato/domain/order/dao/OrderRepository.java
- src/main/java/iampotato/iampotato/domain/order/domain/Order.java
- src/main/java/iampotato/iampotato/domain/order/dto/OrderDetailResponse.java
- src/main/java/iampotato/iampotato/domain/order/exception/OrderException.java
- src/main/java/iampotato/iampotato/domain/order/exception/OrderExceptionGroup.java
- src/main/java/iampotato/iampotato/domain/orderitem/domain/OrderItem.java
- src/main/java/iampotato/iampotato/domain/review/domain/Review.java
- src/main/java/iampotato/iampotato/domain/review/domain/ReviewStatus.java
- src/main/java/iampotato/iampotato/global/exception/ExceptionController.java
- #45 
<br/>
- 주문내역 가져오는 api  및 기능 개발
- swagger 에서 테스트를위한 initDb 주문 데이터 추가 
<br/>
close #45
> Feat/get ordered list(#45)

- src/main/java/iampotato/iampotato/domain/customer/api/CustomerApi.java
- src/main/java/iampotato/iampotato/domain/customer/application/CertifyCustomerService.java
- src/main/java/iampotato/iampotato/domain/customer/application/CustomerSignInService.java
- src/main/java/iampotato/iampotato/domain/customer/application/CustomerSignUpService.java
- src/main/java/iampotato/iampotato/domain/customer/dao/CustomerRepository.java
- src/main/java/iampotato/iampotato/domain/customer/domain/Customer.java
- src/main/java/iampotato/iampotato/domain/customer/dto/CertifyCustomerRequest.java
- src/main/java/iampotato/iampotato/domain/customer/dto/SignInRequest.java
- src/main/java/iampotato/iampotato/domain/customer/dto/SignUpRequest.java
- src/main/java/iampotato/iampotato/domain/customer/dto/TokenResponse.java
- src/main/java/iampotato/iampotato/domain/customer/exception/CustomerException.java
- src/main/java/iampotato/iampotato/domain/customer/exception/CustomerExceptionGroup.java
- #65 
<br/>
- #65 이슈가 main 브랜치에 올바르게 커밋되지 않는 이슈가 있어서 revert 진행하였습니다.
<br/>
- Customer 관련된 모든 파일들
<br/>
- 직접 코드 1:1로 매핑하여 오류 수정
<br/>
- X
> fix: fix many erorrs (#70)

- src/main/java/iampotato/iampotato/domain/item/dao/ItemRepository.java
- src/main/java/iampotato/iampotato/domain/item/domain/Item.java
- src/main/java/iampotato/iampotato/domain/item/domain/Items.java
- src/main/java/iampotato/iampotato/domain/itemoption/dao/ItemOptionRepository.java
- src/main/java/iampotato/iampotato/domain/itemoption/domain/ItemOptions.java
- src/main/java/iampotato/iampotato/domain/order/api/OrderApi.java
- src/main/java/iampotato/iampotato/domain/order/application/OrderService.java
- src/main/java/iampotato/iampotato/domain/order/dao/OrderRepository.java
- src/main/java/iampotato/iampotato/domain/order/domain/Order.java
- src/main/java/iampotato/iampotato/domain/order/dto/OrderPostRequest.java
- src/main/java/iampotato/iampotato/domain/order/dto/OrderPostResponse.java
- src/main/java/iampotato/iampotato/domain/orderitem/domain/OrderItem.java
- src/main/java/iampotato/iampotato/domain/store/dto/detail/StoreDetailItems.java
- #69 
<br/>
- 주문 등록 서비스 기능 및 API 개발
close #69
> Feat/order service(#69)

- src/main/java/iampotato/iampotato/domain/store/dto/search/StoreSearchResponse.java
- src/main/java/iampotato/iampotato/domain/store/dto/todaydiscount/StoreTodayDiscountResponse.java
- #73 
<br/>
- 누락된 api 수정
<br/>
close #73
> fix : modify api spec

- src/main/java/iampotato/iampotato/domain/item/api/ItemController.java
- src/main/java/iampotato/iampotato/domain/item/application/ItemService.java
- src/main/java/iampotato/iampotato/domain/item/dao/ItemRepository.java
- src/main/java/iampotato/iampotato/domain/item/dto/ItemRequest.java
- src/main/java/iampotato/iampotato/domain/item/dto/ItemResponse.java
- src/main/java/iampotato/iampotato/domain/item/exception/ItemException.java
- src/main/java/iampotato/iampotato/domain/item/exception/ItemExceptionGroup.java
- src/main/java/iampotato/iampotato/global/exception/ExceptionController.java
- #75 
<br/>
- 아이템(상품) 정보를 가져오는 기능 및 API 개발
<br/>
close #75
> Feat/develop get item(#75)

- src/main/java/iampotato/iampotato/InitDb.java
- #78 
<br/>
- 예시 데이터를 추가했습니다.
<br/>
> feat : add initDb stores

- src/main/java/iampotato/iampotato/InitDb.java
- src/main/java/iampotato/iampotato/domain/store/dto/detail/StoreDetailItems.java
- src/main/java/iampotato/iampotato/domain/store/dto/detail/StoreDetailResponse.java
- #78 
<br/>
- 데이터 추가 및 response 수정
<br/>
> Feat/update init db(#78)

- src/main/java/iampotato/iampotato/InitDb.java
- src/main/java/iampotato/iampotato/domain/store/dto/detail/StoreDetailItems.java
- src/main/java/iampotato/iampotato/domain/store/dto/detail/StoreDetailResponse.java
- #78 
<br/>
- 데이터 수정 및 추가
<br/>
> Revert "Feat/update init db(#78)"

- src/main/java/iampotato/iampotato/InitDb.java
> feat : fix data

- src/main/java/iampotato/iampotato/domain/owner/dao/OwnerRepository.java
- src/main/java/iampotato/iampotato/domain/ownerstore/application/OwnerStoreService.java
- src/main/java/iampotato/iampotato/domain/ownerstore/dao/OwnerStoreRepository.java
- src/main/java/iampotato/iampotato/domain/ownerstore/domain/OwnerStore.java
- src/main/java/iampotato/iampotato/domain/store/api/StoreApi.java
- src/main/java/iampotato/iampotato/domain/store/application/StoreService.java
- src/main/java/iampotato/iampotato/domain/store/dto/register/StoreRegistrationRequest.java
- src/main/java/iampotato/iampotato/domain/store/dto/register/StoreRegistrationResponse.java
- #76 
<br/>
- 가게 등록 기능 및 API 를 추가했습니다. 최초등록에서 최소 정보만 등록하고 추후 업데이트를 통해 정보를 추가 등록할 수 있게 할 예정입니다.
<br/>
close #76
> Feat/develop post store(#76)

- src/main/java/iampotato/iampotato/domain/review/domain/ReviewResult.java
- src/main/java/iampotato/iampotato/domain/review/domain/Reviews.java
- src/main/java/iampotato/iampotato/domain/store/dto/detail/StoreDetailItemOptions.java
- src/main/java/iampotato/iampotato/domain/store/dto/detail/StoreDetailResponse.java
- #88 
<br/>
- dto 필드명 수정 및 추가
<br/>
> Refacotr/dto field(#88)

- src/main/java/iampotato/iampotato/domain/store/api/StoreApi.java
- src/main/java/iampotato/iampotato/domain/store/application/StoreService.java
- src/main/java/iampotato/iampotato/domain/store/domain/Store.java
- src/main/java/iampotato/iampotato/domain/store/dto/update/StoreUpdateRequest.java
- src/main/java/iampotato/iampotato/domain/store/dto/update/StoreUpdateResponse.java
- src/main/java/iampotato/iampotato/domain/storeoperationhour/domain/StoreOperationHour.java
- src/main/java/iampotato/iampotato/domain/storeoperationhour/domain/StoreOperationHours.java
- #90 
<br/>
- 가게 업데이트 로직 및 api 추가
<br/>
> Feat/update store(#90)

- src/main/java/iampotato/iampotato/InitDb.java
- src/main/java/iampotato/iampotato/domain/owner/api/OwnerApi.java
- src/main/java/iampotato/iampotato/domain/owner/application/OwnerService.java
- src/main/java/iampotato/iampotato/domain/owner/dao/OwnerRepository.java
- src/main/java/iampotato/iampotato/domain/owner/domain/Owner.java
- src/main/java/iampotato/iampotato/domain/owner/dto/OwnerAuthorizeRequest.java
- src/main/java/iampotato/iampotato/domain/owner/dto/OwnerAuthorizeResponse.java
- src/main/java/iampotato/iampotato/domain/owner/dto/OwnerSignUpRequest.java
- src/main/java/iampotato/iampotato/domain/owner/dto/OwnerSignUpResponse.java
- src/main/java/iampotato/iampotato/domain/owner/dto/OwnerUnauthorizedResponse.java
- src/main/java/iampotato/iampotato/domain/owner/exception/OwnerException.java
- src/main/java/iampotato/iampotato/domain/owner/exception/OwnerExceptionGroup.java
- src/main/java/iampotato/iampotato/global/exception/ExceptionController.java
- #93
<br/>
- owner 등록 기능 및 API 추가
<br/>
close #93
> Feat/post owner(#93)

- src/main/java/iampotato/iampotato/InitDb.java
> feat : modify data

- src/main/java/iampotato/iampotato/domain/order/application/OrderService.java
- src/main/java/iampotato/iampotato/domain/order/domain/Order.java
- src/main/java/iampotato/iampotato/domain/order/dto/OrderPostRequest.java
- #99
<br/>
- discontPrice 를 주문필드에 추가
<br/>
close #99
> Feat/fix order field(#99)

- src/main/java/iampotato/iampotato/domain/item/domain/Items.java
- src/main/java/iampotato/iampotato/domain/store/api/StoreApi.java
- src/main/java/iampotato/iampotato/domain/store/application/StoreService.java
- src/main/java/iampotato/iampotato/domain/store/dto/search/StoreSearchResponse.java
- #102 
<br/>
- 검색시 가게명 아이템 구분
- 검색시 아이템일시 해당하는 아이템명 반환
<br/>
> Feat/search update(#102)

- src/main/java/iampotato/iampotato/InitDb.java
- src/main/java/iampotato/iampotato/domain/order/application/OrderService.java
- src/main/java/iampotato/iampotato/domain/order/dto/OrderDetailResponse.java
- src/main/java/iampotato/iampotato/domain/review/domain/Review.java
- src/main/java/iampotato/iampotato/domain/review/domain/ReviewDetail.java
- src/main/java/iampotato/iampotato/domain/review/domain/Reviews.java
- #104
<br/>
- 리뷰 내용 추가
<br/>
close #104
> Feat/review content(#104)

- src/main/java/iampotato/iampotato/InitDb.java
- #78 
<br/>
- 이미지 데이터 수정
<br/>
> feat : update img

- src/main/java/iampotato/iampotato/domain/review/api/ReviewApi.java
- src/main/java/iampotato/iampotato/domain/review/application/ReviewService.java
- src/main/java/iampotato/iampotato/domain/review/dao/ReviewRepository.java
- src/main/java/iampotato/iampotato/domain/review/domain/Review.java
- src/main/java/iampotato/iampotato/domain/review/domain/ReviewDetail.java
- src/main/java/iampotato/iampotato/domain/review/dto/ReviewContentPostRequest.java
- src/main/java/iampotato/iampotato/domain/review/dto/ReviewContentPostResponse.java
- #107 
<br/>
- 사용자가 리뷰를 등록하는 기능 추가
<br/>
close #107
> Feat/post review(#107)

- src/main/java/iampotato/iampotato/InitDb.java
- src/main/java/iampotato/iampotato/domain/customer/application/CustomUserDetailsService.java
- src/main/java/iampotato/iampotato/domain/customer/dto/TokenResponse.java
- src/main/java/iampotato/iampotato/domain/owner/api/OwnerApi.java
- src/main/java/iampotato/iampotato/domain/owner/application/OwnerService.java
- src/main/java/iampotato/iampotato/domain/owner/application/OwnerSignInService.java
- src/main/java/iampotato/iampotato/domain/owner/dao/OwnerRepository.java
- src/main/java/iampotato/iampotato/domain/owner/domain/Owner.java
- src/main/java/iampotato/iampotato/domain/store/application/StoreService.java
- src/main/java/iampotato/iampotato/global/config/SecurityConfig.java
- #110
<br/>
- owner login 기능 추가
<br/>
close #110
> Feat/owner login(#110)

- src/main/java/iampotato/iampotato/InitDb.java
- src/main/java/iampotato/iampotato/domain/order/api/OrderApi.java
- src/main/java/iampotato/iampotato/domain/order/application/OrderService.java
- src/main/java/iampotato/iampotato/domain/order/dao/OrderRepository.java
- src/main/java/iampotato/iampotato/domain/order/domain/Order.java
- src/main/java/iampotato/iampotato/domain/order/domain/OrderStatus.java
- src/main/java/iampotato/iampotato/domain/order/dto/OrderAcceptRequest.java
- src/main/java/iampotato/iampotato/domain/order/dto/OrderAcceptResponse.java
- src/main/java/iampotato/iampotato/domain/order/dto/OrderOwnerRequest.java
- src/main/java/iampotato/iampotato/domain/order/dto/OrderOwnerResponse.java
- src/main/java/iampotato/iampotato/domain/order/dto/OrderRejectRequest.java
- src/main/java/iampotato/iampotato/domain/order/dto/OrderRejectResponse.java
- src/main/java/iampotato/iampotato/domain/owner/api/OwnerApi.java
- src/main/java/iampotato/iampotato/domain/owner/application/OwnerService.java
- src/main/java/iampotato/iampotato/domain/owner/dao/OwnerRepository.java
- src/main/java/iampotato/iampotato/domain/owner/domain/Owner.java
- src/main/java/iampotato/iampotato/domain/owner/dto/OwnerStoresResponse.java
- src/main/java/iampotato/iampotato/domain/store/domain/Store.java
- #108 
<br/>
- 점주 가게 가져오기, 해당 가게의 주문요청 가져오기, 주문 수락, 주문 거절 기능 및 API 개발
<br/>
> Feat/accept order(#108)

- src/main/java/iampotato/iampotato/InitDb.java
- src/main/java/iampotato/iampotato/domain/order/api/OrderApi.java
- src/main/java/iampotato/iampotato/domain/order/application/OrderService.java
- src/main/java/iampotato/iampotato/domain/order/dao/OrderRepository.java
- src/main/java/iampotato/iampotato/domain/order/dto/OrderRecentDiscountsResponse.java
- #113
<br/>
- 최근할인내역 가져오는 기능 및 api 개발
<br/>
> Feat/get recent discounts(#113)

- src/main/java/iampotato/iampotato/InitDb.java
- https://github.com/sayingpotato/Backend/issues/78
<br/>
- Data Visualization을 위한 dummy data script 작성
<br/>
- initDb.java
<br/>
- 스크립트 작성
<br/>
- X
> add: add some dummy data using initDB (#78)

- src/main/java/iampotato/iampotato/InitDb.java
- src/main/java/iampotato/iampotato/domain/item/domain/ItemCategory.java
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
- https://github.com/sayingpotato/Backend/issues/78
<br/>
- 더미 데이터에 다양한 시간대가 분포하도록 수정, 타임존 문제 해결
<br/>
- initDb
<br/>
- 코드 수정
<br/>
- X
> fix: fix some dummy data (#78)
